parameters:
  # For customizing the deployment path in non-PR builds
  - name: deployBasePath
    type: string
    default: ''

  # Skip the component governance detection step (injected by a pipeline decorator from an
  # internal extension) by default because we run it separately. Since all our pipelines
  # in each branch install the same packages, only one pipeline (currently the daily release)
  # needs to run detection.
  - name: skipComponentGovernanceDetection
    type: boolean
    default: true

variables:
  ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/heads/')) }}:
    isPR: true
    targetBranch: 'origin/$(System.PullRequest.TargetBranch)'
    # Deploy PRs under "pull/####" unless otherwise requested
    # (this is also accessed as process.env.DEPLOYBASEPATH)
    deployBasePath: ${{ coalesce(parameters.deployBasePath, 'pull/$(System.PullRequest.PullRequestNumber)') }}
  ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
    isPR: false
    targetBranch: ''
    # Deploy master under "heads/branchname" unless otherwise requested
    deployBasePath: ${{ coalesce(parameters.deployBasePath, replace(variables['Build.SourceBranch'], 'refs/', '')) }}

  skipComponentGovernanceDetection: ${{ parameters.skipComponentGovernanceDetection }}
