pr: none
trigger: none

# Customize build number to include major version
# Example: v8_20201022.1
name: 'v8_$(Date:yyyyMMdd)$(Rev:.r)'

pool: '1ES-Host-Ubuntu'

schedules:
  # minute 0, hour 7 in UTC (11pm in UTC-8), any day of month, any month, days 1-5 of week (M-F)
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?tabs=yaml&view=azure-devops#supported-cron-syntax
  - cron: '0 7 * * 1-5'
    # will be 12am during daylight savings time unless trigger is updated
    displayName: 'Daily release (Sunday-Thursday at 11pm PST)'
    branches:
      include:
        - master

workspace:
  clean: all

steps:
  - template: .devops/templates/tools.yml

  - script: |
      git config user.name "UI Build"
      git config user.email "phantantai9800@gmail.com"
      git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/taidevops/taiui.git
    displayName: Authenticate git for pushes

  - task: Bash@3
    inputs:
      filePath: yarn-ci.sh
    displayName: yarn

  - script: |
      yarn generate-version-files
    displayName: Generate version files

  - script: |
      yarn run:published build --production --no-cache
    displayName: yarn build
