pr:
  - master

# There's a separate pipeline for CI which also uses this file, but with a trigger override in the UI
# https://dev.azure.com/uifabric/fabricpublic/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=164&view=Tab_Triggers
trigger: none

pool: '1ES-Host-Ubuntu'

jobs:
  - job: BuildTestLint
    workspace:
      clean: all
    steps:

      - task: Bash@3
        inputs:
          filePath: yarn-ci.sh
        displayName: yarn
