pr: none
trigger: none

# Customize build number to include major version
# Example: v1_20201212.1
name: 'v1_$(Date:yyyyMMdd)$(Rev:.r)'

pool: 'ubuntu'

schedules:
  - cron: '0 7 * * 1-5'
    # will be 12am during daylight savings time unless trigger is updated
    displayName: 'Daily release (Sunday-Thursday at 11pm PST)'
    branches:
      include:
        - master

workspace:
  clean: all

steps:
  - task: Bash@3
    inputs:
      filePath: yarn-ci.sh
    displayName: yarn
